// This file is automatically generated. Do not edit it directly.

// Your Opix credentials
export const CLIENT_ID = "5703bc31028814106f35c95bb61e09c4";
export const API_KEY = "opx_c2862cf4de64f44eacdae610593f14dc41cb13449edbff9553ce59e70c863ccc";

// Import your Opix SDK factory
import { createClient } from "./sdk";

// Import the Opix client like this:
// import { opix } from "@/integrations/opix/client";

export const opix = createClient(CLIENT_ID, API_KEY);
